default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= Settings.database.host %>
  username: <%= Settings.database.username %>
  password: <%= Settings.database.password %>
  database: <%= Settings.database.database %>

development:
  <<: *default
test:
  <<: *default
porduction:
  <<: *default
