database:
  host: localhost
  database: birthday_email_development
  username: databse_username
  password: database_password
redis:
  host: localhost
  port: 6379
  namespace: birthday_email_development
